In [1]:
print('hii')

hii


In [5]:
pip install ffmpeg-python

Note: you may need to restart the kernel to use updated packages.


In [1]:
import ffmpeg

In [3]:
import ffmpeg

def convert_video_to_audio(video_file_path, audio_file_path):
    try:
        # Load the video file
        stream = ffmpeg.input(video_file_path)

        # Extract audio from the video
        audio = stream.audio

        # Save the extracted audio to the specified file
        ffmpeg.output(audio, audio_file_path).run()

        print(f"Audio successfully saved to {audio_file_path}")

    except ffmpeg.Error as e:
        print(f"An error occurred: {e.stderr.decode('utf-8')}")

# Example usage
video_file = r'/home/hemil/Desktop/LLM/videoplayback.mp4'  # Replace with your video file path
audio_file = 'output_audio.mp3'  # Replace with your desired audio file path

convert_video_to_audio(video_file, audio_file)

ffmpeg version n7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.2.1 (GCC) 20250207
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-frei0r --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable

Audio successfully saved to output_audio.mp3


[out#0/mp3 @ 0x5fb9a955a600] video:0KiB audio:13571KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.002483%
size=   13571KiB time=00:14:28.51 bitrate= 128.0kbits/s speed=16.6x    


In [1]:
pip install -U openai-whisper

  Using cached openai-whisper-20240930.tar.gz (800 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      <string>:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "/home/hemil/Desktop/LLM/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/home/hemil/Desktop/LLM/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/hemil/Desktop/LLM/.venv/lib/python3.13/site-p

In [ ]:
import whisper

model = whisper.load_model("base")
result = model.transcribe('output_audio.mp3')
#save it in txt file

{'text': " I used to believe we were burning on the edge of something beautiful Something beautiful, selling a dream, smoking mirrors keep us waiting on the miracle All the miracles They go through the darkest of days having some heartbreak away Never let you go, never let me down Oh it's been a hell of a fight driving the edge of a night Never let you go, never let me down Don't you give up, nah nah nah I won't give up, nah nah nah Let me love you, let me love you Don't you give up, nah nah nah I won't give up, nah nah nah Let me love you, let me love you Don't fall asleep, I thought we got a million miles ahead of us Miles ahead of us, all that we need is our road away Can't you know we're good enough, yeah, we're good enough They go through the darkest of days having some heartbreak away Never let you go, never let me down Oh it's been a hell of a fight driving the edge of a night Never let you go, never let me down Don't you give up, nah nah nah I won't give up, nah nah nah Let me 

In [9]:
import whisper

# Load the Whisper model
model = whisper.load_model("base")  # You can use "small", "medium", or "large" for better accuracy

# Transcribe the audio file
audio_file = "output_audio.mp3"  # Replace with the path to your audio file
result = model.transcribe(audio_file)

# Extract the transcribed text
transcribed_text = result["text"]

# Save the transcribed text to a .txt file
output_txt_file = "transcribed_text.txt"  # Name of the output text file
with open(output_txt_file, "w") as file:
    file.write(transcribed_text)

print(f"Transcription saved to {output_txt_file}")

Transcription saved to transcribed_text.txt


In [1]:
pip install langchain_huggingface

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 9.6 MB/s eta 0:00:00ta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 8.7 MB/s eta 0:00:0000:010:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 759.5/759.5 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 9.3 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.2/13.2 MB 8.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 8.8 MB/s eta 0:00:0000:0100:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 7.1 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
import langchain_huggingface

In [3]:
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline
import os


# os.environ['HF_HOME'] = 'D:/huggingface_cache'


llm = HuggingFacePipeline.from_model_id(
    model_id='TinyLlama/TinyLlama-1.1B-Chat-v1.0',
    task='text-generation',
    pipeline_kwargs=dict(
        temperature=0.5,
        max_new_tokens=100
    )
)
model = ChatHuggingFace(llm=llm)


result = model.invoke("What is the capital of Gujarat")


print(result.content)


/home/hemil/Desktop/LLM/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


KeyboardInterrupt: 

In [4]:
train_loader = DataLoader(dataset, batch_size=16)

NameError: name 'DataLoader' is not defined

In [6]:
from torch.utils.data import DataLoader, Dataset

# Example dataset (replace with your actual dataset)
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# Create a dummy dataset
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
dataset = MyDataset(data)

# Create the DataLoader
train_loader = DataLoader(dataset, batch_size=2, shuffle=True)

# Iterate through the DataLoader
for batch in train_loader:
    print(batch)

tensor([6, 5])
tensor([4, 1])
tensor([10,  2])
tensor([8, 3])
tensor([9, 7])


In [7]:
import torch
torch.cuda.empty_cache()

In [8]:
optimizer.zero_grad()
for i, data in enumerate(train_loader):
    outputs = model(data)
    loss = criterion(outputs)
    loss.backward()
    if (i + 1) % accumulation_steps == 0:
        optimizer.step()
        optimizer.zero_grad()

NameError: name 'optimizer' is not defined

In [4]:
from langchain.llms import Ollama
ollama = Ollama(base_url="http://localhost:11434",
                model="summarizer")
print(ollama('who are you'))

I am an expert in summarizing complex information into concise, easily digestible versions. I aim to preserve key details while conveying essential insights and ideas. When provided with a text, I aim to distill it down to its most critical points, highlighting the main concepts, takeaways, and relationships between them.

Think of me as a trained researcher or analyst who has been instructed to synthesize information from various sources into a clear, concise narrative. My goal is to assist you by providing an accurate representation of the original text, free from unnecessary repetition or extraneous details.

What specific text would you like me to summarize?


In [1]:
import streamlit as st
import torch

st.title("Minimal Torch Test")
st.write(f"PyTorch version: {torch.__version__}")

2025-03-17 23:30:48.942 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:30:49.155 
  command:

    streamlit run /home/hemil/Desktop/LLM/.venv/lib/python3.13/site-packages/ipykernel_launcher.py [ARGUMENTS]
2025-03-17 23:30:49.158 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:30:49.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:30:49.172 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:30:49.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:30:49.174 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.


In [2]:
# app.py
import streamlit as st

st.title("Minimal Streamlit App")
st.write("Hello, Streamlit!")

2025-03-17 23:33:44.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:33:44.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:33:44.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:33:44.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:33:44.486 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-17 23:33:44.492 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
